name: CI test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  FunctionalTest:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Source branch checkout
      uses: actions/checkout@v2

    - name: LNST Setup
      run: bash .github/lnst_setup.sh

    - name: SimpleNetworkRecipe ping test
      run: |
        export PATH="/root/.local/bin:$PATH"
        venv_path=$(poetry env info -p)
        sudo "$venv_path"/bin/python3 .github/runner.py

  ENRT_All_Test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"

    - name: Source branch checkout
      uses: actions/checkout@v2

    - name: LNST Setup
      run: bash .github/lnst_setup.sh

    - name: Run all ENRT recipes
      run: |
        export PATH="/root/.local/bin:$PATH"
        venv_path=$(poetry env info -p)
        sudo "$venv_path"/bin/python3 .github/runner_all_enrt.py

  ImportsCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Source branch checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install pylint

      - name: Imports check
        run: |
          pylint --disable=all --enable=W0611 lnst
